import re


QUESTION_START_PATTERN = re.compile(
    r"^\s*(?:Q(?:uestion)?\s*)?(\d+)[\.\):-]\s*(.+)$",
    re.IGNORECASE,
)

OPTION_PATTERN = re.compile(
    r"^\s*[\(\[]?([A-Ha-h])[\)\].:-]\s*(.+)$"
)


def extract_questions(text: str) -> list[dict]:
    """
    Extract question blocks and options from OCR/extracted text.

    Returns a list of dictionaries containing:
    - question_number
    - question_text
    - options
    - question_type
    - source_pages
    - extraction_confidence
    - review_status
    """

    lines = text.splitlines()

    questions = []
    current_question = None
    current_page = None

    for raw_line in lines:
        line = raw_line.strip()

        if not line:
            continue

        # Detect page markers generated by our PDF/OCR pipeline.
        page_match = re.match(r"^\[PAGE\s+(\d+)\]$", line, re.IGNORECASE)

        if page_match:
            current_page = int(page_match.group(1))
            continue

        # Detect question starts.
        question_match = QUESTION_START_PATTERN.match(line)

        if question_match:
            # Save the previous question.
            if current_question is not None:
                questions.append(current_question)

            current_question = {
                "question_number": question_match.group(1),
                "question_text": question_match.group(2).strip(),
                "options": {},
                "question_type": "unknown",
                "source_pages": str(current_page) if current_page else None,
                "extraction_confidence": 0.0,
                "review_status": "review",
            }

            continue

        # Detect options.
        option_match = OPTION_PATTERN.match(line)

        if option_match and current_question is not None:
            option_key = option_match.group(1).upper()
            option_text = option_match.group(2).strip()

            current_question["options"][option_key] = option_text
            continue

        # If this isn't a question or option, treat it as continuation
        # text for the current question.
        if current_question is not None:
            current_question["question_text"] += " " + line

    # Save the final question.
    if current_question is not None:
        questions.append(current_question)

    # Calculate a basic confidence score.
    for question in questions:
        has_number = bool(question["question_number"])
        has_text = bool(question["question_text"].strip())
        option_count = len(question["options"])

        if option_count >= 2:
            question["question_type"] = "MCQ"

        if has_number and has_text and option_count >= 2:
            question["extraction_confidence"] = 0.95
            question["review_status"] = "extracted"

        elif has_number and has_text:
            question["extraction_confidence"] = 0.70
            question["review_status"] = "review"

        else:
            question["extraction_confidence"] = 0.40
            question["review_status"] = "uncertain"

    return questions